### ISSUE TITLE
IndexError: list index out of range at very beginning of alignment stage

### ISSUE THREAD

**Issue by kubu4** [MikeAxtell/ShortStack#143]
Here's my command:

```bash
ShortStack \
--genomefile "${genome_fasta}" \
--readfile ${trimmed_fastqs_list} \
--known_miRNAs ${deep_dive_data_dir}/${mirbase_mature_fasta_version} \
--dn_mirna \
--threads ${threads} \
--outdir ${output_dir_top}/ShortStack
```

Error message:

```python
ShortStack version 4.0.2

Beginning run
Options:
{   'adapter': None,
    'align_only': False,
    'autotrim': False,
    'autotrim_key': 'TCGGACCAGGCTTCATTCCCC',
    'bamfile': None,
    'dicermax': 24,
    'dicermin': 21,
    'dn_mirna': True,
    'genomefile': '/home/shared/8TB_HDD_01/sam/gitrepos/deep-dive/D-Apul/data/Amil/ncbi_dataset/data/GCF_013753865.1/GCF_013753865.1_Amil_v2.1_genomic.fa',
    'known_miRNAs': '/home/shared/8TB_HDD_01/sam/gitrepos/deep-dive/data/mirbase-mature-v22.1.fa',
    'locifile': None,
    'locus': None,
    'mincov': 1,
    'mmap': 'u',
    'nohp': False,
    'outdir': '/home/shared/8TB_HDD_01/sam/gitrepos/deep-dive/D-Apul/output/13-Apul-sRNAseq-ShortStack/ShortStack',
    'pad': 200,
    'readfile': [],
    'show_secondaries': False,
    'strand_cutoff': 0.8,
    'threads': 40}
Required executable RNAfold : /home/sam/programs/mambaforge/envs/ShortStack4_env/bin/RNAfold
Required executable strucVis : /home/sam/programs/mambaforge/envs/ShortStack4_env/bin/strucVis
Required executable bowtie : /home/sam/programs/mambaforge/envs/ShortStack4_env/bin/bowtie
Required executable bowtie-build : /home/sam/programs/mambaforge/envs/ShortStack4_env/bin/bowtie-build
Required executable ShortTracks : /home/sam/programs/mambaforge/envs/ShortStack4_env/bin/ShortTracks
Required executable wigToBigWig : /home/sam/programs/mambaforge/envs/ShortStack4_env/bin/wigToBigWig
Required executable samtools : /home/sam/programs/mambaforge/envs/ShortStack4_env/bin/samtools

Beginning alignment phase

Creating browser tracks by readlength and strand using ShortTracks
Traceback (most recent call last):
  File "/home/sam/programs/mambaforge/envs/ShortStack4_env/bin/ShortStack", line 3582, in <module>
    merged_bam, read_count = align(args, fai, trimmed_files)
  File "/home/sam/programs/mambaforge/envs/ShortStack4_env/bin/ShortStack", line 792, in align
    callShortTracks(final_bams[0], 'readlength', True)
IndexError: list index out of range
```

Do you happen to have any suggestions on how to troubleshoot this? Thanks in advance for any ideas you might have!

**Comment by kubu4** [comment]
Gah! I'm now seeing (of course, as soon I created the issue) that the readfile list is empty! Sorry for the trouble!
